var dir_27747142951285b09bacafa002e92b5f =
[
    [ "ConversationHistory.cpp", "ConversationHistory_8cpp.html", null ],
    [ "ConversationHistory.h", "ConversationHistory_8h.html", "ConversationHistory_8h" ],
    [ "DbManager.cpp", "DbManager_8cpp.html", null ],
    [ "DbManager.h", "DbManager_8h.html", "DbManager_8h" ],
    [ "GroupMessage.cpp", "GroupMessage_8cpp.html", null ],
    [ "GroupMessage.h", "GroupMessage_8h.html", "GroupMessage_8h" ],
    [ "ICommandHandler.h", "ICommandHandler_8h.html", "ICommandHandler_8h" ],
    [ "IEntity.h", "IEntity_8h.html", "IEntity_8h" ],
    [ "IRepository.h", "IRepository_8h.html", "IRepository_8h" ],
    [ "main.cpp", "backend_2src_2main_8cpp.html", "backend_2src_2main_8cpp" ],
    [ "Message.cpp", "Message_8cpp.html", "Message_8cpp" ],
    [ "Message.h", "Message_8h.html", "Message_8h" ],
    [ "MessageRepository.cpp", "MessageRepository_8cpp.html", null ],
    [ "MessageRepository.h", "MessageRepository_8h.html", "MessageRepository_8h" ],
    [ "OfflineMessage.cpp", "OfflineMessage_8cpp.html", null ],
    [ "OfflineMessage.h", "OfflineMessage_8h.html", "OfflineMessage_8h" ],
    [ "OfflineQueueRepository.cpp", "OfflineQueueRepository_8cpp.html", null ],
    [ "OfflineQueueRepository.h", "OfflineQueueRepository_8h.html", "OfflineQueueRepository_8h" ],
    [ "ProtocolParser.cpp", "ProtocolParser_8cpp.html", null ],
    [ "ProtocolParser.h", "ProtocolParser_8h.html", "ProtocolParser_8h" ],
    [ "Session.cpp", "Session_8cpp.html", null ],
    [ "Session.h", "Session_8h.html", "Session_8h" ],
    [ "SessionRepository.cpp", "SessionRepository_8cpp.html", null ],
    [ "SessionRepository.h", "SessionRepository_8h.html", "SessionRepository_8h" ],
    [ "User.cpp", "User_8cpp.html", "User_8cpp" ],
    [ "User.h", "User_8h.html", "User_8h" ],
    [ "UserRepository.cpp", "UserRepository_8cpp.html", null ],
    [ "UserRepository.h", "UserRepository_8h.html", "UserRepository_8h" ]
];